#SERVER
server.port=8081
server.servlet.context-path=/samuel

spring.application.name=samuel-estudos

#DATASOURCE USANDO HIKARI GERENCIADOR DO POOL DE CONEXOES
spring.datasource.url=jdbc:postgresql://localhost:5432/db-samuel
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.connectionTimeout=20000
spring.datasource.hikari.maximumPoolSize=5
